FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn mlflow scikit-learn pandas numpy scipy joblib pyarrow pydantic pyyaml optuna
COPY src/ /app/src/
COPY configs/ /app/configs/
ENV PYTHONPATH=/app/src
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]